# Generated by Django 6.0.3 on 2026-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_last_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='penalty',
            field=models.CharField(default='Do 20 pushups', max_length=200),
        ),
    ]
