# Generated by Django 6.0.3 on 2026-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='penalty',
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
