# Generated by Django 6.0.3 on 2026-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('fitness', 'Fitness'), ('health', 'Health')], default='study', max_length=20),
        ),
    ]
